apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photoapp.fullname" . }}-secrets
  labels:
    {{- include "photoapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.api.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.api.google.clientSecret | quote }}
  OIDC_ISSUER_URL: {{ .Values.api.oidc.issuerUrl | quote }}
  OIDC_CLIENT_ID: {{ .Values.api.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.api.oidc.clientSecret | quote }}
